language: python
python:
  - "2.6"
  - "2.7"
node_js:
  - "0.10"
services:
  - riak
  - redis-server
install:
  - "pip install coveralls --use-wheel"
  - "python setup.py install"
script:
  - coverage run --source=archer `which trial` archer
after_success:
  - coveralls
