language: python
python:
  - "2.6"
  - "2.7"
node_js:
  - "0.10"
services:
  - riak
  - redis-server
before_install:
  - sudo apt-get install neo4j
  - sudo service neo4j-service start
install:
  - "pip install coveralls --use-wheel"
  - "pip install -e ."
script:
  - coverage run --source=archer `which trial` archer
after_success:
  - coveralls
