language: python
python:
  - "2.6"
  - "2.7"
node_js:
  - "0.10"
services:
  - riak
  - redis-server
  - neo4j
install:
  - "pip install coveralls --use-wheel"
  - "pip install -e ."
script:
  - coverage run --source=archer `which trial` archer
after_success:
  - coveralls
